###

POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Robert Lewandowski",
    "age": "25",
    "email": "LewanPolski01@gmail.com"
}


###

GET http://localhost:9000/api/users HTTP/1.1


###

GET http://localhost:9000/api/users/6372a74ee8ceeaaf66fbbc15 HTTP/1.1

###

PUT http://localhost:9000/api/users/6372a6cee8ceeaaf66fbbc12 HTTP/1.1
Content-Type: application/json

{
    "name": "Luis Suarez",
    "age": "34",
    "email": "CharruaGunslinger@gmail.com"
}

###

DELETE http://localhost:9000/api/users/6372a74ee8ceeaaf66fbbc15 HTTP/1.1

